spring.application.name=mlfstats

spring.datasource.url=jdbc:mariadb://localhost:3306/mlf
spring.datasource.username=mlf
spring.datasource.password=trivial
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true

name.stromkabelsalat.mlfstats.category-ids=9941,9942
